(()=>{
 const select=document.createElement('select');select.id='practice-kind';select.setAttribute('aria-label','學習或刷題');select.innerHTML='<option value="quiz">刷題模式</option><option value="learn">學習模式</option>';document.querySelector('.controls').prepend(select);
 const panel=document.createElement('section');panel.id='learning-panel';panel.hidden=true;document.querySelector('header').append(panel);
 let kind=new URLSearchParams(location.search).get('practice')==='learn'?'learn':'quiz';select.value=kind;
 const read=()=>{try{return JSON.parse(localStorage.getItem('pathology:found-features')||'{}')}catch{return {}}};
 const detail=document.querySelector('#detailbox'),detailPanel=document.createElement('section');detailPanel.id='detail-learning';detailPanel.hidden=true;detail.querySelector('.detail-grid').prepend(detailPanel);
 function saveFound(input){if(!cur)return;const f=read(),key=cur.id+':'+input.dataset.feature;f[key]=input.checked;try{localStorage.setItem('pathology:found-features',JSON.stringify(f))}catch{}document.querySelectorAll('[data-feature]').forEach(x=>{if(x.dataset.feature===input.dataset.feature)x.checked=input.checked});updateProgress()}
 function updateProgress(){if(!cur)return;const f=read(),count=(cur.pairs||[]).filter((_,i)=>f[cur.id+':'+i]).length;document.querySelectorAll('.learning-progress').forEach(x=>x.textContent=`已找到 ${count} / ${(cur.pairs||[]).length} 項特徵`)}
 function detailUpdate(){detailPanel.hidden=kind!=='learn';detail.classList.toggle('with-learning',kind==='learn');if(kind!=='learn'||!cur){detailPanel.innerHTML='';return}const f=read();detailPanel.innerHTML=`<p class="workspace-label">${esc(cur.id)}</p><h2>${esc(cur.organ)} · ${esc(cur.diagnosis)}</h2><h3>找找看</h3><p class="learning-progress note"></p>${cur.pairs?.length?cur.pairs.map((p,i)=>`<label class="feature"><input type="checkbox" data-feature="${i}" ${f[cur.id+':'+i]?'checked':''}><span>${esc(p)}</span></label>`).join(''):'<p>導讀待補</p>'}`;detailPanel.querySelectorAll('[data-feature]').forEach(x=>x.onchange=()=>saveFound(x));updateProgress()}
 new MutationObserver(detailUpdate).observe(detail,{attributes:true,attributeFilter:['open']});
 function update(){detailUpdate();const learning=kind==='learn';document.body.classList.toggle('learning',learning);panel.hidden=!learning;document.querySelector('#form').hidden=learning;if(!learning){panel.innerHTML='';return}document.querySelector('#reveal').className='reveal';if(!cur){panel.textContent='此範圍沒有切片。';return}const s=cur,found=read();panel.innerHTML=`<p class="workspace-label">${esc(s.id)}</p><h2>${esc(s.organ)}</h2><p class="learning-dx">${esc(s.diagnosis)}<br>${esc(s.zh)}</p><label for="learn-slide">選擇切片</label><select id="learn-slide">${Q.map(x=>`<option value="${esc(x.id)}" ${x.id===s.id?'selected':''}>${esc(x.id)} · ${esc(x.zh||x.diagnosis)}</option>`).join('')}</select><h3>找找看</h3><p class="learning-progress note"></p><p class="note">依現有講義 Description 列出，勾選代表你已找到。</p>${s.pairs?.length?s.pairs.map((p,i)=>`<label class="feature"><input type="checkbox" data-feature="${i}" ${found[s.id+':'+i]?'checked':''}><span>${esc(p)}</span></label>`).join(''):'<p>導讀待補：目前尚無授課辨識清單。</p>'}<p class="note">參考圖待核對後補上。</p><a href="${GUIDE+encodeURIComponent(s.id)}" target="_blank" rel="noopener">開啟切片導讀 ↗</a><button id="learn-next" type="button">下一張切片 →</button>`;panel.querySelector('#learn-slide').onchange=e=>{requestedSlide=e.target.value;next();update()};panel.querySelector('#learn-next').onclick=()=>{next();update()};panel.querySelectorAll('[data-feature]').forEach(input=>input.onchange=()=>saveFound(input));updateProgress();if(document.querySelector('#view').value!=='full'){document.querySelector('#view').value='full';render()}}
 select.onchange=()=>{kind=select.value;update()};new MutationObserver(update).observe(document.querySelector('#qtitle'),{childList:true,characterData:true,subtree:true});update();
})();
