(()=>{
 const select=document.createElement('select');select.id='practice-kind';select.setAttribute('aria-label','學習或刷題');select.innerHTML='<option value="quiz">刷題模式</option><option value="learn">學習模式</option>';document.querySelector('.controls').prepend(select);
 const panel=document.createElement('section');panel.id='learning-panel';panel.hidden=true;document.querySelector('header').append(panel);
 let kind=new URLSearchParams(location.search).get('practice')==='learn'?'learn':'quiz';select.value=kind;
 const read=()=>{try{return JSON.parse(localStorage.getItem('pathology:found-features')||'{}')}catch{return {}}};
 let resumed=false,quizTitle=document.querySelector('#qtitle').textContent;const detail=document.querySelector('#detailbox'),detailPanel=document.createElement('section');detailPanel.id='detail-learning';detailPanel.hidden=true;detail.querySelector('.detail-grid').prepend(detailPanel);
 const panelStates=new Map();
 function keepPanel(node){if(!node.dataset.slide)return;panelStates.set(node.id+':'+node.dataset.slide,{top:node.scrollTop,open:node.querySelector('.learning-fold')?.open});}
 function restorePanel(node,id){node.dataset.slide=id;const saved=panelStates.get(node.id+':'+id);if(!saved)return;const fold=node.querySelector('.learning-fold');if(fold&&saved.open!==undefined)fold.open=saved.open;node.scrollTop=saved.top;}
 function saveFound(input){if(!cur)return;const f=read(),key=cur.id+':'+input.dataset.feature;f[key]=input.checked;try{localStorage.setItem('pathology:found-features',JSON.stringify(f))}catch{}document.querySelectorAll('[data-feature]').forEach(x=>{if(x.dataset.feature===input.dataset.feature)x.checked=input.checked});updateProgress()}
 const absent=p=>/本片無|本片沒有|本片未見|not present in this slide/i.test(p);
 const translation=(s,text)=>window.LEARNING_DESCRIPTIONS?.[s.id]?.[text]||'';
 const featureItems=s=>(s.pairs||[]).map((text,index)=>({text,index}));
 function features(s,f){const items=featureItems(s),present=items.filter(x=>!absent(x.text)),missing=items.filter(x=>absent(x.text));return (present.length?present.map(x=>`<label class="feature"><input type="checkbox" data-feature="${x.index}" ${f[s.id+':'+x.index]?'checked':''}><span>${esc(x.text)}${translation(s,x.text)?`<small class="feature-zh">${esc(translation(s,x.text))}</small>`:""}</span></label>`).join(''):'<p>目前尚無本片可找的特徵清單。</p>')+(missing.length?`<section class="note"><h3>課堂補充 · 本片未見</h3><ul>${missing.map(x=>`<li>${esc(x.text)}</li>`).join('')}</ul></section>`:'')}
 function updateProgress(){if(!cur)return;const f=read(),items=featureItems(cur).filter(x=>!absent(x.text)),count=items.filter(x=>f[cur.id+':'+x.index]).length;document.querySelectorAll('.learning-progress').forEach(x=>{x.textContent=`已找到 ${count} / ${items.length} 項特徵`;x.hidden=!items.length})}
 function detailUpdate(){keepPanel(detailPanel);detailPanel.hidden=kind!=='learn';detail.classList.toggle('with-learning',kind==='learn');if(kind!=='learn'||!cur){detailPanel.innerHTML='';return}const f=read();detailPanel.innerHTML=`<p class="workspace-label">${esc(cur.id)}</p><h2>${esc(cur.organ)}</h2><p class="learning-dx">${esc(cur.diagnosis)} · ${esc(cur.zh)}</p><details class="learning-fold" open><summary>辨識清單</summary><p class="learning-progress note"></p>${cur.pairs?.length?features(cur,f):"<p>辨識重點待補</p>"}</details>`;restorePanel(detailPanel,cur.id);detailPanel.querySelectorAll('[data-feature]').forEach(x=>x.onchange=()=>saveFound(x));updateProgress()}
 new MutationObserver(detailUpdate).observe(detail,{attributes:true,attributeFilter:['open']});
 function update(){keepPanel(panel);detailUpdate();const learning=kind==='learn';document.body.classList.toggle('learning',learning);panel.hidden=!learning;document.querySelector('#form').hidden=learning;if(!learning){panel.innerHTML='';const t=document.querySelector('#qtitle');if(t.textContent.startsWith('第 '))quizTitle=t.textContent;if(t.textContent!==quizTitle)t.textContent=quizTitle;return}document.querySelector('#reveal').className='reveal';if(!cur){panel.textContent='此範圍沒有切片。';return}const s=cur,found=read();const title=document.querySelector('#qtitle');if(title.textContent.startsWith('第 '))quizTitle=title.textContent;const titleText=s.diagnosis+(s.zh?' · '+s.zh:'');if(title.textContent!==titleText)title.textContent=titleText;panel.innerHTML=`<p class="workspace-label">${esc(s.id)}</p><h2>${esc(s.organ)}</h2><p class="learning-dx">${esc(s.diagnosis)} · ${esc(s.zh)}</p><label for="learn-slide">選擇切片</label><select id="learn-slide">${pool().map(x=>`<option value="${esc(x.id)}" ${x.id===s.id?'selected':''}>${esc(x.id)} · ${esc(x.diagnosis)}</option>`).join('')}</select>${s.pairs?.length?`<details class="learning-fold" open><summary>辨識清單</summary><p class="learning-progress note"></p>${features(s,found)}</details>`:"<p class=\"note\">辨識重點待補</p>"}${s.exam===1?`<a href="${GUIDE+encodeURIComponent(s.id)}" target="_blank" rel="noopener">開啟切片導讀 ↗</a>`:""}`;restorePanel(panel,s.id);panel.querySelector('#learn-slide').onchange=e=>{requestedSlide=e.target.value;next();update()};panel.querySelectorAll('[data-feature]').forEach(input=>input.onchange=()=>saveFound(input));updateProgress();panel.querySelector('a')?.addEventListener('click',()=>{Detail20x.remember();try{localStorage.setItem('pathology:return',JSON.stringify({id:s.id,url:location.pathname+'?slide='+encodeURIComponent(s.id)+'&practice=learn&resume=1'}))}catch{}});if(!resumed&&new URLSearchParams(location.search).get('resume')==='1'){resumed=true;Detail20x.open(s)}if(document.querySelector('#view').value!=='full'){document.querySelector('#view').value='full';render()}}
 select.onchange=()=>{kind=select.value;if(kind==='learn'&&!cur)next();update()};new MutationObserver(update).observe(document.querySelector('#qtitle'),{childList:true,characterData:true,subtree:true});update();
})();
