/* 圓形FN18視野：連續平移，背景載圖。來源地址與GUID不在公開程式。 */
window.Detail20x=(()=>{
 const $=id=>document.getElementById(id),dialog=document.createElement('dialog');
 dialog.id='detailbox';dialog.setAttribute('aria-label','圓形視野瀏覽');
 dialog.innerHTML=`<div class="modalbar"><strong>圓形視野瀏覽</strong><button id="detail-close">關閉 ×</button></div><details class="viewer-help"><summary>操作說明</summary><p class="hint">點低倍圖選位置；直接拖曳圓形內圖片。方向鍵¼視野，Shift＋方向鍵½視野。10×／40×依FN18模擬。</p></details><div class="detail-grid"><details class="detail-low" open><summary>低倍定位圖</summary><div class="detail-map"><img id="detail-map" alt="點選整張玻片的任意位置"><div id="detail-marker"></div></div></details><div class="detail-high"><div class="detail-nav"><button id="field-10" aria-pressed="true">10× 視野</button><button id="field-40" aria-pressed="false">40× 視野</button></div><p id="detail-status" role="status"></p><div id="detail-field" style="position:relative;width:min(100%,65vh);aspect-ratio:1;margin:auto"><div id="detail-canvas" tabindex="0" aria-label="可拖曳的圓形視野" style="width:100%;height:100%;border-radius:50%;overflow:hidden;touch-action:none;contain:paint"></div><div id="detail-scale" style="position:absolute;bottom:12%;left:50%;transform:translateX(-50%);background:#ffffffd9;text-align:center;font-size:12px;pointer-events:none"><span>100 µm</span><div style="border-bottom:3px solid #222"></div></div></div><div class="detail-nav"><button id="detail-left" aria-label="圓形視野往左">←</button><button id="detail-up" aria-label="圓形視野往上">↑</button><button id="detail-down" aria-label="圓形視野往下">↓</button><button id="detail-right" aria-label="圓形視野往右">→</button><button id="detail-retry">重新載入</button></div></div></div>`;
 document.body.appendChild(dialog);
 let viewer,slide,cell,mode=10,highItem,ready=false,serial=0,failed=false;
 const available=s=>!!s?.selectable20x;
 const geometry=()=>slide.selectable20x,diameter=()=>mode===10?1800:450;
 function bounds(){const g=geometry();return cell?{x:cell.highBounds?.x??cell.c*g.width/slide.cols,y:cell.highBounds?.y??cell.r*g.height/slide.rows,width:cell.highBounds?.width??g.width/slide.cols,height:cell.highBounds?.height??g.height/slide.rows}:{x:0,y:0,width:g.width,height:g.height};}
 function source(g,base){const tiles=new Set(g.tiles),bases=new Map();for(const part of g.parts||[])for(const key of part.tiles)bases.set(key,part.base);return {width:g.width,height:g.height,tileSize:g.tileSize,minLevel:0,maxLevel:0,getLevelScale:()=>1,getTileUrl:(level,x,y)=>`${bases.get(`${y},${x}`)||base}/r${y}c${x}.jpg`,tileExists:(level,x,y)=>tiles.has(`${y},${x}`)};}
 function update(){if(!ready||!dialog.open)return;const g=geometry(),b=bounds(),c=viewer.viewport.getCenter(true),d=diameter()/g.mpp,left=Math.max(b.x,c.x*g.width-d/2),top=Math.max(b.y,c.y*g.width-d/2),right=Math.min(b.x+b.width,c.x*g.width+d/2),bottom=Math.min(b.y+b.height,c.y*g.width+d/2);$('detail-marker').style.cssText=`left:${(left-b.x)/b.width*100}%;top:${(top-b.y)/b.height*100}%;width:${Math.max(0,right-left)/b.width*100}%;height:${Math.max(0,bottom-top)/b.height*100}%`;
 const loading=viewer.imageLoader.jobsInProgress>0;$('detail-status').textContent=failed?'部分細節未載入，請按重新載入':`${mode}× 視野 · 圓形直徑 ${(diameter()/1000).toFixed(2)} mm${loading?' · 細節載入中…':''}`;}
 function field(n,center){mode=n;highItem?.setOpacity(n===40?1:0);for(const m of [10,40])$('field-'+m).setAttribute('aria-pressed',m===n);const g=geometry(),c=center||viewer.viewport.getCenter(),w=diameter()/(g.width*g.mpp);viewer.viewport.fitBounds(new OpenSeadragon.Rect(c.x-w/2,c.y-w/2,w,w),true);$('detail-scale').style.width=`${100/diameter()*100}%`;update();remember();}
 function remember(){if(!ready||!viewer||!slide)return;const p=viewer.viewport.getCenter();try{localStorage.setItem("pathology:view:"+slide.id,JSON.stringify({x:p.x,y:p.y,mode,cell:cell?{r:cell.r,c:cell.c}:null}))}catch{}}
 function open(s,c=null,fx=.5,fy=.5){const restore=arguments.length===1;let saved=null;if(restore){try{saved=JSON.parse(localStorage.getItem("pathology:view:"+s.id)||"null")}catch{}if(saved?.cell)c=s.cells.find(x=>x.r===saved.cell.r&&x.c===saved.cell.c)||null;}if(!available(s))return;const current=++serial;viewer?.destroy();slide=s;cell=c;ready=false;failed=false;highItem=null;mode=10;const g=geometry(),b=bounds(),base=s.assetBase||`slides/${s.id}`;$('detail-map').src=c?`${base}/r${c.r}c${c.c}.jpg`:`${base}/overview.jpg`;$('detail-map').alt=c?'點選此格子的任意位置':'點選整張玻片的任意位置';$('detail-status').textContent='載入中…';if(!dialog.open)dialog.showModal();
 viewer=OpenSeadragon({id:'detail-canvas',showNavigationControl:false,animationTime:.18,blendTime:.12,imageLoaderLimit:6,maxImageCacheCount:matchMedia('(pointer:coarse)').matches?64:120,minPixelRatio:.5,visibilityRatio:.1,constrainDuringPan:true,gestureSettingsMouse:{scrollToZoom:false,clickToZoom:false,dblClickToZoom:false},gestureSettingsTouch:{pinchToZoom:false,clickToZoom:false,dblClickToZoom:false},maxZoomPixelRatio:8});
 const start=()=>{if(current!==serial)return;ready=true;field(saved?.mode===40?40:10,new OpenSeadragon.Point(Number.isFinite(saved?.x)?saved.x:(b.x+fx*b.width)/g.width,Number.isFinite(saved?.y)?saved.y:(b.y+fy*b.height)/g.width));};
 // 概覽先鋪底：新分塊未到時仍有同位置影像。
 viewer.addSimpleImage({url:`${base}/overview.jpg`,width:1,success:()=>{if(current!==serial)return;viewer.addTiledImage({tileSource:source(g,s.hiBase||`slides/${s.id}/hi`),width:1,success:()=>{if(current!==serial)return;if(s.ultra&&s.ultraBase)viewer.addTiledImage({tileSource:source(s.ultra,s.ultraBase),width:1,opacity:0,success:e=>{highItem=e.item;start();}});else start();}});},error:()=>{$('detail-status').textContent='概覽載入失敗，請按重新載入';}});
 viewer.addHandler('animation-finish',remember);viewer.addHandler('animation',update);viewer.addHandler('tile-loaded',update);viewer.addHandler('tile-drawn',update);viewer.addHandler('tile-load-failed',()=>{failed=true;update();});}
 $('detail-map').onclick=e=>{if(!ready)return;const g=geometry(),b=bounds(),r=e.currentTarget.getBoundingClientRect();field(mode,new OpenSeadragon.Point((b.x+(e.clientX-r.left)/r.width*b.width)/g.width,(b.y+(e.clientY-r.top)/r.height*b.height)/g.width));};
 for(const n of [10,40])$('field-'+n).onclick=()=>ready&&field(n);
 function move(dx,dy,speed=1){if(!ready)return;const g=geometry(),step=diameter()/(g.width*g.mpp)*.25*speed;viewer.viewport.panBy(new OpenSeadragon.Point(dx*step,dy*step));viewer.viewport.applyConstraints();}
 for(const [id,dx,dy] of [['detail-left',-1,0],['detail-right',1,0],['detail-up',0,-1],['detail-down',0,1]])$(id).onclick=()=>move(dx,dy);
 const keys={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};dialog.addEventListener('keydown',e=>{if(!dialog.open||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||!keys[e.key])return;e.preventDefault();move(...keys[e.key],e.shiftKey?2:1);});
 $('detail-retry').onclick=()=>{const g=geometry(),b=bounds(),c=ready?viewer.viewport.getCenter():new OpenSeadragon.Point((b.x+b.width/2)/g.width,(b.y+b.height/2)/g.width);open(slide,cell,(c.x*g.width-b.x)/b.width,(c.y*g.width-b.y)/b.height);};
 $('detail-close').onclick=()=>{remember();dialog.close()};dialog.addEventListener('cancel',remember);dialog.addEventListener('close',()=>{++serial;viewer?.destroy();viewer=null;ready=false;});
 return {available,open,remember};
})();
